### ISSUE TITLE
По условиям задачи это использовать нельзя!

### ISSUE THREAD

**Issue by DevEvolution** [tortikpirog/cinemaHall#4]
https://github.com/tortikpirog/cinemaHall/blob/79315964f964c8bebf47f4e6baf550754941f757/hallController.js#L146

![image](https://user-images.githubusercontent.com/31969483/188282739-c83b4288-af1b-45ae-b7d0-c72920879000.png)

**Comment by tortikpirog** [comment]
я думал ты не заметишь и прокатит ))
ладно подумаю как можно закостылить под древнее говно

**Comment by tortikpirog** [comment]
`formattedDates.push(dates[i].toLocaleString('ru', dateOptions))`

вот так можно
